[env:uMule_Receiver]
platform = ststm32
board = nucleo_g474re
extra_scripts = force_fpu.py
board_build.ldscript = STM32G474XX_FLASH.ld
platform_packages = toolchain-gccarmnoneeabi@~1.120301.0

build_src_filter =
    +<Core/Src/*.c>
    +<Core/Startup/*.s>
    +<Drivers/STM32G4xx_HAL_Driver/Src/*.c>
    -<Drivers/STM32G4xx_HAL_Driver/Src/*_template.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/*.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/*.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/*.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c>
    +<micro_ros_stm32cubemx_utils/Src/*.c>

build_flags =
    -ICore/Inc
    -IDrivers/STM32G4xx_HAL_Driver/Inc
    -IDrivers/STM32G4xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32G4xx/Include
    -IDrivers/CMSIS/Include
    -IMiddlewares/Third_Party/FreeRTOS/Source/include
    -IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    -IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
    -DSTM32G474xx
    -DUSE_HAL_DRIVER
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
    
    -Imicro_ros_stm32cubemx_utils/microros_static_library/libmicroros/microros_include
    -Imicro_ros_stm32cubemx_utils/Inc
    -Lmicro_ros_stm32cubemx_utils/microros_static_library/libmicroros
    -lmicroros
    -lc
    -lm
    -lnosys

[platformio]
include_dir = Core/Inc
src_dir = ./